FROM      ubuntu
MAINTAINER Evgeny Safronov "division494@gmail.com"

RUN echo "deb http://archive.ubuntu.com/ubuntu precise main universe" > /etc/apt/sources.list
RUN apt-get update

RUN apt-get install -y git