#!/bin/bash

LOGDIR="/var/log/cocaine-tornado"
PIDDIR="/var/run/cocaine-tornado"

/usr/sbin/useradd cocaine -m || true

# Create directory for logs
if [ ! -d "$LOGDIR" ]; then
    mkdir -p $LOGDIR
fi
chown -R cocaine $LOGDIR

# Create directory for PID
if [ ! -d "$PIDDIR" ]; then
    mkdir -p $PIDDIR
fi
chown -R cocaine $PIDDIR

# Autostart
/usr/sbin/update-rc.d cocaine-tornado-proxy defaults

#DEBHELPER#
