#!/usr/bin/env python
from opster import Dispatcher
#TODO: Package name cocaine.tools.tools is not funny. May be move it one layer up?
import sys
from cocaine.tools.tools import ToolsExecutor, NodeExecutor, coloredOutput, ToolsError, printError


__author__ = 'EvgenySafronov <division494@gmail.com>'


DESCRIPTION = ''
DEFAULT_HOST = 'localhost'
DEFAULT_PORT = 10053


class Locator(object):
    options = [
        ('h', 'host', DEFAULT_HOST, 'hostname'),
        ('p', 'port', DEFAULT_PORT, 'port'),
        ('', 'color', False, 'enable colored output'),
        ('', 'timeout', 1.0, 'timeout, s')
    ]

    def __init__(self, host=DEFAULT_HOST, port=DEFAULT_PORT, color=False, timeout=False):
        self.host = host
        self.port = port
        self.color = color
        self.timeout = timeout
        self.tools = ToolsExecutor()
        if not color:
            coloredOutput.disable()


def middleware(func):
    def extract_dict(source, *keys):
        dest = {}
        for k in keys:
            dest[k] = source.pop(k, None)
        return dest

    def inner(*args, **kwargs):
        opts = extract_dict(kwargs, 'host', 'port', 'color', 'timeout')
        if func.__name__ == 'help_inner':
            return func(*args, **kwargs)
        locator = Locator(**opts)
        return func(locator, *args, **kwargs)
    return inner


d = Dispatcher()
appDispatcher = Dispatcher(globaloptions=Locator.options, middleware=middleware)
profileDispatcher = Dispatcher(globaloptions=Locator.options, middleware=middleware)
runlistDispatcher = Dispatcher(globaloptions=Locator.options, middleware=middleware)
crashlogDispatcher = Dispatcher(globaloptions=Locator.options, middleware=middleware)


@d.command()
def info(host=('h', DEFAULT_HOST, 'hostname'),
         port=('p', DEFAULT_PORT, 'port')):
    """
    Shows information about cocaine runtime
    """
    node = NodeExecutor()
    node.executeAction('info', **{
        'host': host,
        'port': port
    })


@appDispatcher.command(name='list')
def app_list(locator):
    """
    Shows installed applications list
    """
    locator.tools.executeAction('app:list', **{
        'host': locator.host,
        'port': locator.port
    })


@appDispatcher.command(usage='--name=NAME', name='view')
def app_view(locator,
             name=('n', '', 'application name')):
    """
    Shows manifest context for application
    """
    locator.tools.executeAction('app:view', **{
        'host': locator.host,
        'port': locator.port,
        'name': name,
        'timeout': locator.timeout
    })


@appDispatcher.command(name='upload')
def app_upload(locator,
               name=('n', '', 'application name'),
               manifest=('', '', 'manifest file name'),
               package=('', '', 'location of the app source package')):
    """
    Uploads application into storage
    """
    tools.executeAction('app:upload', **{
        'host': locator.host,
        'port': locator.port,
        'name': name,
        'manifest': manifest,
        'package': package
    })


@appDispatcher.command(name='remove')
def app_remove(locator,
               name=('n', '', 'application name')):
    """
    Removes application from storage
    """
    tools.executeAction('app:remove', **{
        'host': locator.host,
        'port': locator.port,
        'name': name
    })


@appDispatcher.command(name='start')
def app_start(locator,
              name=('n', '', 'application name'),
              profile=('r', '', 'profile name')):
    """
    Starts application
    """
    node = NodeExecutor()
    node.executeAction('app:start', **{
        'host': locator.host,
        'port': locator.port,
        'name': name,
        'profile': profile
    })


@appDispatcher.command(name='pause')
def app_pause(locator,
              name=('n', '', 'application name')):
    """
    Pauses application
    """
    node = NodeExecutor()
    node.executeAction('app:pause', **{
        'host': locator.host,
        'port': locator.port,
        'name': name
    })

#todo: implement app restart command
#todo: add this command to bash completion


@appDispatcher.command()
def check(locator,
          name=('n', '', 'application name')):
    """
    Checks application status
    """
    node = NodeExecutor()
    node.executeAction('app:check', **{
        'host': locator.host,
        'port': locator.port,
        'name': name
    })


@profileDispatcher.command(name='list')
def profile_list(locator):
    """
    Shows installed profiles list
    """
    tools.executeAction('profile:list', **{
        'host': locator.host,
        'port': locator.port
    })


@profileDispatcher.command(name='view')
def profile_view(locator,
                 name=('n', '', 'profile name')):
    """
    Shows configuration context
    """
    tools.executeAction('profile:view', **{
        'host': locator.host,
        'port': locator.port,
        'name': name
    })


@profileDispatcher.command(name='upload')
def profile_upload(locator,
                   name=('n', '', 'profile name'),
                   profile=('', '', 'path to profile file')):
    """
    Uploads profile into storage
    """
    tools.executeAction('profile:upload', **{
        'host': locator.host,
        'port': locator.port,
        'name': name,
        'manifest': profile
    })


@profileDispatcher.command(name='remove')
def profile_upload(locator,
                   name=('n', '', 'profile name')):
    """
    Removes profile from storage
    """
    tools.executeAction('profile:remove', **{
        'host': locator.host,
        'port': locator.port,
        'name': name
    })


@runlistDispatcher.command(name='list')
def runlist_list(locator):
    """
    Shows uploaded runlists
    """
    tools.executeAction('runlist:list', **{
        'host': locator.host,
        'port': locator.port
    })


@runlistDispatcher.command(name='view')
def runlist_view(locator,
                 name=('n', '', 'name')):
    """
    Shows configuration context for runlist
    """
    tools.executeAction('runlist:view', **{
        'host': locator.host,
        'port': locator.port,
        'name': name
    })


@runlistDispatcher.command(name='upload')
def runlist_upload(locator,
                   name=('n', '', 'name'),
                   runlist=('', '', 'runlist')):
    """
    Uploads runlist with context into storage
    """
    tools.executeAction('runlist:upload', **{
        'host': locator.host,
        'port': locator.port,
        'name': name,
        'manifest': runlist
    })


@runlistDispatcher.command(name='remove')
def runlist_remove(locator,
                   name=('n', '', 'name')):
    """
    Removes runlist from storage
    """
    tools.executeAction('runlist:remove', **{
        'host': locator.host,
        'port': locator.port,
        'name': name
    })


@runlistDispatcher.command(name='add-app')
def runlist_add_app(locator,
                    name=('n', '', 'runlist name'),
                    app=('', '', 'application name'),
                    profile=('', '', 'suggested profile')):
    """
    Adds specified application with profile to runlist
    """
    tools.executeAction('runlist:add-app', **{
        'host': locator.host,
        'port': locator.port,
        'name': name,
        'app': app,
        'profile': profile
    })


@crashlogDispatcher.command(name='list')
def crashlog_list(locator,
                  name=('n', '', 'name')):
    """
    Shows crashlogs list for application
    """
    tools.executeAction('crashlog:list', **{
        'host': locator.host,
        'port': locator.port,
        'name': name
    })


@crashlogDispatcher.command(name='view')
def crashlog_view(locator,
                  name=('n', '', 'name'),
                  timestamp=('t', '', 'timestamp')):
    """
    Shows crashlog for application with specified timestamp
    """
    tools.executeAction('crashlog:view', **{
        'host': locator.host,
        'port': locator.port,
        'name': name,
        'manifest': timestamp
    })


@crashlogDispatcher.command(name='remove')
def crashlog_remove(locator,
                    name=('n', '', 'name'),
                    timestamp=('t', '', 'timestamp')):
    """
    Removes crashlog for application with specified timestamp
    """
    tools.executeAction('crashlog:remove', **{
        'host': locator.host,
        'port': locator.port,
        'name': name,
        'manifest': timestamp
    })


@crashlogDispatcher.command(name='removeall')
def crashlog_removeall(locator,
                       name=('n', '', 'name')):
    """
    Removes all crashlogs for application
    """
    tools.executeAction('crashlog:removeall', **{
        'host': locator.host,
        'port': locator.port,
        'name': name,
        'manifest': None
    })


d.nest('app', appDispatcher, 'application commands')
d.nest('profile', profileDispatcher, 'profile commands')
d.nest('runlist', runlistDispatcher, 'runlist commands')
d.nest('crashlog', crashlogDispatcher, 'crashlog commands')


if __name__ == '__main__':
    if not sys.stdin.isatty():
        coloredOutput.disable()

    tools = ToolsExecutor()
    try:
        d.dispatch()
    except ToolsError as err:
        printError(err)
        exit(1)
